package AminoAcidGUI;

import java.util.LinkedHashMap;

public class Acids {
    public LinkedHashMap<String, String> getAcids() {
        return acids;
    }

    private LinkedHashMap<String, String> acids = new LinkedHashMap<>();

    private static Acids ourInstance = new Acids();

    public static Acids getInstance() {
        return ourInstance;
    }

    private Acids() {
        acids.put("None","");
        acids.put("HBB Human",              "MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH");
        acids.put("HBB Similar",            "MVHLTDAEKSAVSCLWAKVNPDEVGGEALGRLLVVYPWTQRYFDSFGDLSSASAIMGNPKVKAHGKKVITAFNEGLKNLDNLKGTFASLSELHCDKLHVDPENFRLLGNAIVIVLGHHLGKDFTPAAQAAFQKVVAGVATALAHKYH");
        acids.put("HBB S",                  "MVHLTPVEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH");
        acids.put("HBB C",                  "MVHLTPKEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH");
        acids.put("HBB E",                  "MVHLTPEEKSAVTALWGKVNVDEVGGKALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH");
        acids.put("HBA1 Human",             "MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR");
        acids.put("DPH6 Human",             "MRVAALISGGKDSCYNMMQCIAAGHQIVALANLRPAENQVGSDELDSYMYQTVGHHAIDLYAEAMALPLYRRTIRGRSLDTRQVYTKCEGDEVEDLYELLKLVKEKEEVEGISVGAILSDYQRIRVENVCKRLNLQPLAYLWQRNQEDLLREMISSNIQAMIIKVAALGLDPDKHLGKTLDQMEPYLIELSKKYGVHVCGEGGEYETFTLDCPLFKKKIIVDSSEVVIHSADAFAPVAYLRFLELHLEDKVSSVPDNYRTSNYIYNF");
        acids.put("DPH6 Mouse",             "MRVAALISGGKDSCYNMMQCIAEGHQIVALANLRPDENQVESDELDSYMYQTVGHHAIDLYAEAMALPLYRRAIRGRSLETGRVYTQCEGDEVEDLYELLKLVKEKEEIEGVSVGAILSDYQRGRVENVCKRLNLQPLAYLWQRNQEDLLREMIASNIKAIIIKVAALGLDPDKHLGKTLVEMEPYLLELSKKYGVHVCGEGGEYETFTLDCPLFKKKIVVDSSEAVMHSADAFAPVAYLRLSRLHLEEKVSSVPADDETANSIHSS");
        acids.put("DPH6 Rat",               "MRVAALISGGKDSCYNMMRCIAEGHQIVALANLRPDDNQVESDELDSYMYQTVGHHAIDLYAEAMALPLYRRTIRGRSLETGRVYTRCEGDEVEDLYELLKLVKEKEEIEGVSVGAILSDYQRVRVENVCKRLNLQPLAYLWQRNQEDLLREMIASNIEAIIIKVAALGLDPDKHLGKTLGEMEPYLLELSKKYGVHVCGEGGEYETFTLDCPLFKKKIVVDTSEAVIHSADAFAPVAYLRLSGLHLEEKVSSVPGDDETTSYIHNS");
        acids.put("DPH6 ZebraFish",         "MRVVGLISGGKDSCFNMLQCVSAGHSIVALANLRPADHAASDELDSYMYQTVGHQAVDLIAEAMGLPLYRRTIEGSSVHIDREYSPTDGDEVEDLYQLLKHVKEEMHVDGVSVGAILSDYQRVRVENVCARLQLQPLAYLWRRDQAALLSEMISSGLHAILIKVAAFGLHPDKHLGKSLAEMELYLHELSEKYGVHICGEGGEYETFTLDCPLFKKKIIIDATETVIHSDDAFAPVGFLRFTKMHTEDKTEGSGGPPPPSLSACPCQSAIDRMTEELEYADKTADVQRECPSHTQSTWQLDEGCEVSHSSSSSGFQWISGLSALPSEHPDIQSQAQHVFTLLQSRLQEMGSALRHVLLVHLYVSSMQDFGLINSIYSRLFTHNPPARVCVQASLPVGQQLQMDVLLQDQTKASPSSSSSVCEEECFPQRETLHVQSVSHWAPANIGPYSQATQVQLCFLLTAAASAVFSTVFYISTSAAQWLSGQHCGFTARRSLV");
        acids.put("DPH6 D. melanogaster",   "MRVVAMVSGGKDSCYNMMQCVAEGHEIVALANLHPKDRDELDSFMYQTVGHMGIEILASAMGLPLYRRETKGKSTQTGKQYVPTDDDEVEDLYSLLETCKHELQVDAVAVGAILSDYQRVRVENVCSRLNLISLAYLWRRDQTELLQEMIDCQVHAIIIKVAALGLVPDRHLGKSLREMQPHLLKMRDKYGLNVCGEGGEYETFTLDCPLFRQRIVVEDIQTIISSADPICPVGYINFTKLTLQPKEAAGAASSGGNEVVFVKRSLDYISDLNESTYSDLSDPDFSETELELIEKETRLRESLSQSELISRSNSFGRHLAATASSPIPIVTKSASVDEPTAAAAPILGGVGGPPICSTSACASMLLTTTADGLSSLASSQSQGGGHGLGSSTAAVCGSLSLAISSLGLSANTCCHPGGAGGGGGVGIGVGAGAGAGAPSATTQPPSPLKYEREFRPLANEARAAINAKGWMWLAGIQGSGTEGIEQGMQQALDTLRDLCQAKGYDLQDLCYVTLYVRSIGEYPLLNRVYHRAFDFHNPPTRVCVECPLPDGCHVVMEAIAYRQPVAGTISSAEERDREGEETAAALLNGRRNTMHVQGISHWAPANIGPYSQSTRIGDITYISGQIALVPGSMTIIEGGIRPQCKLTLRHISRIAKAMNAHGQLRDVVHGICFVTHPAFIGEARRQWERRTTNAIMDYIVLPALPREALVEWQVWAHTHNDRFDYEETGCSVGDYTISIRRRWNYENNCAAIVCYVSTGLASSTTQLTQLSDDILGNHCRLAQAVNAEHLDEIFTYVVNRLLKDYPLAKKQASQPTNSATPPATPTQPGGAGGDQQQPVPAIHLKLFYQVNAAPATDLLLQALHDFRLKCQDTAAIVYTVLPACSLHNFSTFLSICGVRHE");
        acids.put("DPH6 C. elegans",        "MQVVGLISGGKDSCYNLMCAVREGHQIVALANLHPPKDAKSDELDSYMYQSVGADGVELYGEAMQLPLYRREITGEPKNQKSDYEKTDGDEVEDLFELLCEVKKHHPEVKGVSAGAILSSYQKVRVEDICRRLDLVPLCFLWEREQNGLLAEMVENGLDAILIKVAAIGLGEQHLGKTLSEMAPIMKVLQDKYGVHPCGEGGEFESFVRDCPLFKKRIVIDETETVTHQDDPIAPVFYLRLKKMHLEDK");
        acids.put("DPH6 S. cerevisiae",     "MKFIALISGGKDSFYNIFHCLKNNHELIALGNIYPKESEEQELDSFMFQTVGHDLIDYYSKCIGVPLFRRSILRNTSNNVELNYTATQDDEIEELFELLRTVKDKIPDLEAVSVGAILSSYQRTRVENVCSRLGLVVLSYLWQRDQAELMGEMCLMSKDVNNVENDTNSGNKFDARIIKVAAIGLNEKHLGMSLPMMQPVLQKLNQLYQVHICGEGGEFETMVLDAPFFQHGYLELIDIVKCSDGEVHNARLKVKFQPRNLSKSFLLNQLDQLPVPSIFGNNWQDLTQNLPKQQAKTGEQRFENHMSNALPQTTINKTNDKLYISNLQSRKSETVEKQSEDIFTELADILHSNQIPRNHILSASLLIRDMSNFGKINKIYNEFLDLSKYGPLPPSRACVGSKCLPEDCHVQLSVVVDVKNTGKEKINKNKGGLHVQGRSYWAPCNIGPYSQSTWLNDDANQVSFISGQIGLVPQSMEILGTPLTDQIVLALQHFDTLCETIGAQEKLLMTCYISDESVLDSVIKTWAFYCSNMNHRSDLWMDKSDDVEKCLVLVKISELPRGAVAEFGGVTCKRLIVDDNDSDKKEREENDDVSTVFQKLNLNIEGFHNTTVSAFGYNRNFITGFVDSREELELILEKTPKSAQITLYYNPKEIITFHHHIGYYPVEKLFDYRGKEHRFGLHIRS");
        acids.put("Thymidylate synthase",   "MPVAGSELPRRPLPPAAQERDAEPRPPHGELQYLGQIQHILRCGVRKDDRTGTGTLSVFGMQARYSLRDEFPLLTTKRVFWKGVLEELLWFIKGSTNAKELSSKGVKIWDANGSRDFLDSLGFSTREEGDLGPVYGFQWRHFGAEYRDMESDYSGQGVDQLQRVIDTIKTNPDDRRIIMCAWNPRDLPLMALPPCHALCQFYVVNSELSCQLYQRSGDMGLGVPFNIASYALLTYMIAHITGLKPGDFIHTLGDAHIYLNHIEPLKIQLQREPRPFPKLRILRKVEKIDDFKAEDFQIEGYNPHPTIKMEMAV");
    }
}
